version: "3.9"

services:
  angular-app:
    container_name: angular-app
    build:
      context: ./angular-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    networks:
      - ms-network

  eureka:
    container_name: eureka
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - ms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      - eureka.instance.hostname=eureka
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

  mysql-product:
    image: mysql:8
    networks:
      - local-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=product
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  product:
    container_name: product
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    networks:
      - local-mysql
      - ms-network
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-product/product?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://product:8087 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 10s
    depends_on:
      mysql-product:
        condition: service_healthy
      eureka:
        condition: service_healthy

  
  mysql-stock:
    image: mysql:8
    networks:
      - local-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=stock
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10


  stock:
    container_name: stock
    build:
      context: ./stock
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - local-mysql
      - ms-network
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-stock/stock?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://stock:8084 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 10s
    depends_on:
      mysql-stock:
        condition: service_healthy
      eureka:
        condition: service_healthy


  mysql-operateur:
    image: mysql:8
    networks:
      - local-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=operateur
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10


  operateur:
    container_name: operateur
    build:
      context: ./operateur
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    networks:
      - local-mysql
      - ms-network
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-operateur/operateur?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://stock:8086 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 10s
    depends_on:
      mysql-operateur:
        condition: service_healthy
      eureka:
        condition: service_healthy

  gateway:
    container_name: gateway
    build:
      context: ./APIGateway
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - ms-network
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - SPRING_PROFILES_ACTIVE=test


networks:
  local-mysql:
  ms-network:
    driver: bridge
