eureka:
  client:
    fetch-registry: "true"
    register-with-eureka: "true"
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: vaccinationMs
          uri: http://localhost:8091/
          predicates:
            - Path=/**
        - id: petMS
          uri: http://localhost:5000/
          predicates:
            - Path=/**
        - id: localMS
          uri: http://localhost:8094/
          predicates:
            - Path=/locals/**
        - id: rewardMS
          uri: http://localhost:8085/
          predicates:
            - Path=/rewards/**
        - id: stock
          uri: http://localhost:8084/
          predicates:
            - Path=/stock/**
        - id: operateur
          uri: http://localhost:8086/
          predicates:
            - Path=/operateur/**
        - id: back-end
          uri: http://localhost:8087/
          predicates:
            - Path=/**
  security:
    user:
      name: root
      password: root

server:
  port: "8888"
